---
title: Connected Technologies
author: Steve Danforth
email: info@connectedtech.com
description: Connected Technologies designs, develops, and manages marketing solutions
  for hospitals using best in class technologies.
baseurl: ''
url: http://connectedtech.com
defaults:
- scope: ''
  values: ''
plugins:
- jekyll-feed
- jekyll-menus
